### ISSUE TITLE
Unable to desrialize custom ROS message

### ISSUE THREAD

**Issue by deepaktalwardt** [fishros/ros2bag_convert#2]
Hi, thanks for open-sourcing this repo, but currently, I'm unable to use it with custom ROS2 messages, although, I was able to get it to work with the example you provided in the README. 

I'm getting the following error when I try to use `ros2bag-convert`
```
Traceback (most recent call last):
  File "/usr/local/bin/ros2bag-convert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ros2bag_convert/main.py", line 14, in main
    data = read_bag.read_from_all_topics(file_url,True)
  File "/usr/local/lib/python3.8/dist-packages/ros2bag_convert/ros2bag_convert/read_bag.py", line 210, in read_from_all_topics
    timestamps, messages = read_from_topic(bag_file, topic_names[i], print_out)
  File "/usr/local/lib/python3.8/dist-packages/ros2bag_convert/ros2bag_convert/read_bag.py", line 182, in read_from_topic
    msg = deserialize_message(messages_cdr[i], msg_type)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/serialization.py", line 42, in deserialize_message
    return _rclpy.rclpy_deserialize(serialized_message, message_type)
rclpy._rclpy_pybind11.RMWError: failed to deserialize ROS message: rmw_serialize: invalid data size, at /tmp/binarydeb/ros-galactic-rmw-cyclonedds-cpp-0.22.4/src/rmw_node.cpp:1537
-
```
Could you help me resolve this? The package with the custom message is built and sourced in this terminal window.

**Comment by deepaktalwardt** [comment]
Please ignore, it was an error on my part. The message size built locally was different from what's in the bag.
